import { Subject, Language, ThemeMode } from './types';
import { Book, Code, Calculator, Database, Cpu, Globe, Shield } from 'lucide-react';

// REPLACE THIS URL WITH YOUR UPLOADED LOGO URL
export const LOGO_URL = 'https://placehold.co/200x80/indigo/white?text=IT+Study+Hub';

export const INITIAL_SUBJECTS: Subject[] = [
  { id: '1', nameEn: 'Intro to Programming', nameAr: 'مبادئ البرمجة', descriptionEn: 'C++ and Python basics', descriptionAr: 'أساسيات C++ وبايثون', icon: 'Code' },
  { id: '2', nameEn: 'Calculus I', nameAr: 'تفاضل وتكامل 1', descriptionEn: 'Limits and Derivatives', descriptionAr: 'النهايات والاشتقاق', icon: 'Calculator' },
  { id: '3', nameEn: 'Discrete Mathematics', nameAr: 'الرياضيات المتقطعة', descriptionEn: 'Logic and Sets', descriptionAr: 'المنطق والمجموعات', icon: 'Book' },
  { id: '4', nameEn: 'Computer Organization', nameAr: 'تنظيم الحاسب', descriptionEn: 'Hardware and Logic Gates', descriptionAr: 'العتاد والبوابات المنطقية', icon: 'Cpu' },
  { id: '5', nameEn: 'Database Systems', nameAr: 'نظم قواعد البيانات', descriptionEn: 'SQL and Normalization', descriptionAr: 'SQL وتصميم القواعد', icon: 'Database' },
  { id: '6', nameEn: 'English for IT', nameAr: 'لغة إنجليزية تقنية', descriptionEn: 'Technical Terminology', descriptionAr: 'المصطلحات التقنية', icon: 'Globe' },
  { id: '7', nameEn: 'Cybersecurity Basics', nameAr: 'أساسيات الأمن السيبراني', descriptionEn: 'Network Security', descriptionAr: 'أمن الشبكات', icon: 'Shield' },
];

export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome to IT Study Hub',
    welcomeSub: 'Your gateway to excellence in Information Technology.',
    searchPlaceholder: 'Search for subjects, files...',
    aboutUs: 'About Us',
    aboutText: 'We bridge the gap between students and knowledge. A dedicated platform for first-year IT resources managed by experts.',
    requestSummary: 'Request a Summary',
    sendRequest: 'Send Request',
    subjects: 'Subjects',
    contactUs: 'Contact Us',
    files: 'Files',
    downloads: 'Downloads',
    rating: 'Rating',
    adminLogin: 'Admin Login',
    dashboard: 'Dashboard',
    manageContent: 'Manage Content',
    upload: 'Upload New File',
    download: 'Download',
    login: 'Login',
    logout: 'Logout',
    copyright: '© 2024 IT Study Hub. All rights reserved.',
    studentName: 'Student Name',
    comments: 'Comments',
    submit: 'Submit',
    success: 'Success!',
    error: 'Error',
    adminPanel: 'Admin Panel',
    stats: 'Statistics',
    recentActivity: 'Recent Activity',
    aiAssistant: 'AI Assistant',
    chatPlaceholder: 'Ask me anything about IT...',
    theme: 'Theme',
    language: 'Language',
    home: 'Home',
    noFiles: 'No files uploaded yet.',
    name: 'Name',
    type: 'Type',
    actions: 'Actions',
    delete: 'Delete',
    cancel: 'Cancel',
    requestSent: 'Your request has been sent successfully!',
    adminUser: 'Username',
    adminPass: 'Password',
    controlPanel: 'Control Panel',
    manageUsers: 'Manage Users',
    addUser: 'Add New User',
    role: 'Role',
    created: 'Created',
  },
  ar: {
    welcome: 'مرحبًا بكم في بوابة تقنية المعلومات',
    welcomeSub: 'بوابتك للتميز في تكنولوجيا المعلومات.',
    searchPlaceholder: 'ابحث عن المواد والملفات...',
    aboutUs: 'من نحن',
    aboutText: 'نحن نجسّر الفجوة بين الطلاب والمعرفة. منصة مخصصة لموارد السنة الأولى في تقنية المعلومات بإدارة خبراء.',
    requestSummary: 'طلب ملخص',
    sendRequest: 'إرسال الطلب',
    subjects: 'المواد الدراسية',
    contactUs: 'اتصل بنا',
    files: 'الملفات',
    downloads: 'التحميلات',
    rating: 'التقييم',
    adminLogin: 'دخول المسؤول',
    dashboard: 'لوحة التحكم',
    manageContent: 'إدارة المحتوى',
    upload: 'رفع ملف جديد',
    download: 'تحميل',
    login: 'دخول',
    logout: 'خروج',
    copyright: '© 2024 بوابة تقنية المعلومات. جميع الحقوق محفوظة.',
    studentName: 'اسم الطالب',
    comments: 'ملاحظات',
    submit: 'إرسال',
    success: 'تم بنجاح!',
    error: 'خطأ',
    adminPanel: 'لوحة الإدارة',
    stats: 'الإحصائيات',
    recentActivity: 'النشاط الأخير',
    aiAssistant: 'المساعد الذكي',
    chatPlaceholder: 'اسألني أي شيء عن التقنية...',
    theme: 'المظهر',
    language: 'اللغة',
    home: 'الرئيسية',
    noFiles: 'لا توجد ملفات مرفوعة بعد.',
    name: 'الاسم',
    type: 'النوع',
    actions: 'إجراءات',
    delete: 'حذف',
    cancel: 'إلغاء',
    requestSent: 'تم إرسال طلبك بنجاح!',
    adminUser: 'اسم المستخدم',
    adminPass: 'كلمة المرور',
    controlPanel: 'لوحة التحكم',
    manageUsers: 'إدارة المستخدمين',
    addUser: 'إضافة مستخدم جديد',
    role: 'الصلاحية',
    created: 'تاريخ الإنشاء',
  },
};

export const THEMES: Record<ThemeMode, { bg: string; text: string; primary: string; secondary: string; card: string }> = {
  light: {
    bg: 'bg-gray-50',
    text: 'text-gray-900',
    primary: 'bg-indigo-600',
    secondary: 'bg-indigo-100',
    card: 'bg-white',
  },
  dark: {
    bg: 'bg-gray-900',
    text: 'text-gray-100',
    primary: 'bg-indigo-500',
    secondary: 'bg-gray-800',
    card: 'bg-gray-800',
  },
  boy: {
    bg: 'bg-blue-50',
    text: 'text-blue-900',
    primary: 'bg-blue-600',
    secondary: 'bg-blue-200',
    card: 'bg-white',
  },
  girl: {
    bg: 'bg-pink-50',
    text: 'text-pink-900',
    primary: 'bg-pink-500',
    secondary: 'bg-pink-200',
    card: 'bg-white',
  },
};